#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HastaneU.Modal
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="HastaneU")]
	public partial class HastaneUDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void InsertPatoVeriler(PatoVeriler instance);
    partial void UpdatePatoVeriler(PatoVeriler instance);
    partial void DeletePatoVeriler(PatoVeriler instance);
    partial void InserttblDemog(tblDemog instance);
    partial void UpdatetblDemog(tblDemog instance);
    partial void DeletetblDemog(tblDemog instance);
    partial void InserttblDoktor(tblDoktor instance);
    partial void UpdatetblDoktor(tblDoktor instance);
    partial void DeletetblDoktor(tblDoktor instance);
    partial void InserttblHasta(tblHasta instance);
    partial void UpdatetblHasta(tblHasta instance);
    partial void DeletetblHasta(tblHasta instance);
    partial void InserttblKoMorbidite(tblKoMorbidite instance);
    partial void UpdatetblKoMorbidite(tblKoMorbidite instance);
    partial void DeletetblKoMorbidite(tblKoMorbidite instance);
    partial void InserttblOperatif(tblOperatif instance);
    partial void UpdatetblOperatif(tblOperatif instance);
    partial void DeletetblOperatif(tblOperatif instance);
    partial void InserttblOpTuru(tblOpTuru instance);
    partial void UpdatetblOpTuru(tblOpTuru instance);
    partial void DeletetblOpTuru(tblOpTuru instance);
    partial void InserttblPatoloji(tblPatoloji instance);
    partial void UpdatetblPatoloji(tblPatoloji instance);
    partial void DeletetblPatoloji(tblPatoloji instance);
    partial void InserttblTakipVerileri(tblTakipVerileri instance);
    partial void UpdatetblTakipVerileri(tblTakipVerileri instance);
    partial void DeletetblTakipVerileri(tblTakipVerileri instance);
    partial void InserttblPosOperatif(tblPosOperatif instance);
    partial void UpdatetblPosOperatif(tblPosOperatif instance);
    partial void DeletetblPosOperatif(tblPosOperatif instance);
    #endregion
		
		public HastaneUDataContext() : 
				base(global::HastaneU.Properties.Settings.Default.HastaneUConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public HastaneUDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public HastaneUDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public HastaneUDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public HastaneUDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<PatoVeriler> PatoVerilers
		{
			get
			{
				return this.GetTable<PatoVeriler>();
			}
		}
		
		public System.Data.Linq.Table<tblDemog> tblDemogs
		{
			get
			{
				return this.GetTable<tblDemog>();
			}
		}
		
		public System.Data.Linq.Table<tblDoktor> tblDoktors
		{
			get
			{
				return this.GetTable<tblDoktor>();
			}
		}
		
		public System.Data.Linq.Table<tblHasta> tblHastas
		{
			get
			{
				return this.GetTable<tblHasta>();
			}
		}
		
		public System.Data.Linq.Table<tblKoMorbidite> tblKoMorbidites
		{
			get
			{
				return this.GetTable<tblKoMorbidite>();
			}
		}
		
		public System.Data.Linq.Table<tblOperatif> tblOperatifs
		{
			get
			{
				return this.GetTable<tblOperatif>();
			}
		}
		
		public System.Data.Linq.Table<tblOpTuru> tblOpTurus
		{
			get
			{
				return this.GetTable<tblOpTuru>();
			}
		}
		
		public System.Data.Linq.Table<tblPatoloji> tblPatolojis
		{
			get
			{
				return this.GetTable<tblPatoloji>();
			}
		}
		
		public System.Data.Linq.Table<tblTakipVerileri> tblTakipVerileris
		{
			get
			{
				return this.GetTable<tblTakipVerileri>();
			}
		}
		
		public System.Data.Linq.Table<tblPosOperatif> tblPosOperatifs
		{
			get
			{
				return this.GetTable<tblPosOperatif>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.PatoVeriler")]
	public partial class PatoVeriler : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _ID;
		
		private string _PatVeriler;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIDChanging(int value);
    partial void OnIDChanged();
    partial void OnPatVerilerChanging(string value);
    partial void OnPatVerilerChanged();
    #endregion
		
		public PatoVeriler()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int ID
		{
			get
			{
				return this._ID;
			}
			set
			{
				if ((this._ID != value))
				{
					this.OnIDChanging(value);
					this.SendPropertyChanging();
					this._ID = value;
					this.SendPropertyChanged("ID");
					this.OnIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PatVeriler", DbType="NVarChar(50)")]
		public string PatVeriler
		{
			get
			{
				return this._PatVeriler;
			}
			set
			{
				if ((this._PatVeriler != value))
				{
					this.OnPatVerilerChanging(value);
					this.SendPropertyChanging();
					this._PatVeriler = value;
					this.SendPropertyChanged("PatVeriler");
					this.OnPatVerilerChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tblDemog")]
	public partial class tblDemog : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _ID;
		
		private System.Nullable<int> _HastaID;
		
		private System.Nullable<int> _Yas;
		
		private System.Nullable<decimal> _Boy;
		
		private System.Nullable<decimal> _Kilo;
		
		private System.Nullable<int> _BMI;
		
		private System.Nullable<int> _Asa;
		
		private string _Dr;
		
		private string _Cins;
		
		private string _Taraf;
		
		private string _Lokalizasyon;
		
		private System.Nullable<int> _Boyut;
		
		private string _KoMor;
		
		private EntityRef<tblHasta> _tblHasta;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIDChanging(int value);
    partial void OnIDChanged();
    partial void OnHastaIDChanging(System.Nullable<int> value);
    partial void OnHastaIDChanged();
    partial void OnYasChanging(System.Nullable<int> value);
    partial void OnYasChanged();
    partial void OnBoyChanging(System.Nullable<decimal> value);
    partial void OnBoyChanged();
    partial void OnKiloChanging(System.Nullable<decimal> value);
    partial void OnKiloChanged();
    partial void OnBMIChanging(System.Nullable<int> value);
    partial void OnBMIChanged();
    partial void OnAsaChanging(System.Nullable<int> value);
    partial void OnAsaChanged();
    partial void OnDrChanging(string value);
    partial void OnDrChanged();
    partial void OnCinsChanging(string value);
    partial void OnCinsChanged();
    partial void OnTarafChanging(string value);
    partial void OnTarafChanged();
    partial void OnLokalizasyonChanging(string value);
    partial void OnLokalizasyonChanged();
    partial void OnBoyutChanging(System.Nullable<int> value);
    partial void OnBoyutChanged();
    partial void OnKoMorChanging(string value);
    partial void OnKoMorChanged();
    #endregion
		
		public tblDemog()
		{
			this._tblHasta = default(EntityRef<tblHasta>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int ID
		{
			get
			{
				return this._ID;
			}
			set
			{
				if ((this._ID != value))
				{
					this.OnIDChanging(value);
					this.SendPropertyChanging();
					this._ID = value;
					this.SendPropertyChanged("ID");
					this.OnIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_HastaID", DbType="Int")]
		public System.Nullable<int> HastaID
		{
			get
			{
				return this._HastaID;
			}
			set
			{
				if ((this._HastaID != value))
				{
					if (this._tblHasta.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnHastaIDChanging(value);
					this.SendPropertyChanging();
					this._HastaID = value;
					this.SendPropertyChanged("HastaID");
					this.OnHastaIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Yas", DbType="Int")]
		public System.Nullable<int> Yas
		{
			get
			{
				return this._Yas;
			}
			set
			{
				if ((this._Yas != value))
				{
					this.OnYasChanging(value);
					this.SendPropertyChanging();
					this._Yas = value;
					this.SendPropertyChanged("Yas");
					this.OnYasChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Boy", DbType="Decimal(5,2)")]
		public System.Nullable<decimal> Boy
		{
			get
			{
				return this._Boy;
			}
			set
			{
				if ((this._Boy != value))
				{
					this.OnBoyChanging(value);
					this.SendPropertyChanging();
					this._Boy = value;
					this.SendPropertyChanged("Boy");
					this.OnBoyChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Kilo", DbType="Decimal(5,2)")]
		public System.Nullable<decimal> Kilo
		{
			get
			{
				return this._Kilo;
			}
			set
			{
				if ((this._Kilo != value))
				{
					this.OnKiloChanging(value);
					this.SendPropertyChanging();
					this._Kilo = value;
					this.SendPropertyChanged("Kilo");
					this.OnKiloChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BMI", DbType="Int")]
		public System.Nullable<int> BMI
		{
			get
			{
				return this._BMI;
			}
			set
			{
				if ((this._BMI != value))
				{
					this.OnBMIChanging(value);
					this.SendPropertyChanging();
					this._BMI = value;
					this.SendPropertyChanged("BMI");
					this.OnBMIChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Asa", DbType="Int")]
		public System.Nullable<int> Asa
		{
			get
			{
				return this._Asa;
			}
			set
			{
				if ((this._Asa != value))
				{
					this.OnAsaChanging(value);
					this.SendPropertyChanging();
					this._Asa = value;
					this.SendPropertyChanged("Asa");
					this.OnAsaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Dr", DbType="NVarChar(50)")]
		public string Dr
		{
			get
			{
				return this._Dr;
			}
			set
			{
				if ((this._Dr != value))
				{
					this.OnDrChanging(value);
					this.SendPropertyChanging();
					this._Dr = value;
					this.SendPropertyChanged("Dr");
					this.OnDrChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Cins", DbType="NVarChar(15)")]
		public string Cins
		{
			get
			{
				return this._Cins;
			}
			set
			{
				if ((this._Cins != value))
				{
					this.OnCinsChanging(value);
					this.SendPropertyChanging();
					this._Cins = value;
					this.SendPropertyChanged("Cins");
					this.OnCinsChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Taraf", DbType="NVarChar(15)")]
		public string Taraf
		{
			get
			{
				return this._Taraf;
			}
			set
			{
				if ((this._Taraf != value))
				{
					this.OnTarafChanging(value);
					this.SendPropertyChanging();
					this._Taraf = value;
					this.SendPropertyChanged("Taraf");
					this.OnTarafChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Lokalizasyon", DbType="NVarChar(150)")]
		public string Lokalizasyon
		{
			get
			{
				return this._Lokalizasyon;
			}
			set
			{
				if ((this._Lokalizasyon != value))
				{
					this.OnLokalizasyonChanging(value);
					this.SendPropertyChanging();
					this._Lokalizasyon = value;
					this.SendPropertyChanged("Lokalizasyon");
					this.OnLokalizasyonChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Boyut", DbType="Int")]
		public System.Nullable<int> Boyut
		{
			get
			{
				return this._Boyut;
			}
			set
			{
				if ((this._Boyut != value))
				{
					this.OnBoyutChanging(value);
					this.SendPropertyChanging();
					this._Boyut = value;
					this.SendPropertyChanged("Boyut");
					this.OnBoyutChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_KoMor", DbType="NVarChar(50)")]
		public string KoMor
		{
			get
			{
				return this._KoMor;
			}
			set
			{
				if ((this._KoMor != value))
				{
					this.OnKoMorChanging(value);
					this.SendPropertyChanging();
					this._KoMor = value;
					this.SendPropertyChanged("KoMor");
					this.OnKoMorChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tblHasta_tblDemog", Storage="_tblHasta", ThisKey="HastaID", OtherKey="ID", IsForeignKey=true)]
		public tblHasta tblHasta
		{
			get
			{
				return this._tblHasta.Entity;
			}
			set
			{
				tblHasta previousValue = this._tblHasta.Entity;
				if (((previousValue != value) 
							|| (this._tblHasta.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._tblHasta.Entity = null;
						previousValue.tblDemogs.Remove(this);
					}
					this._tblHasta.Entity = value;
					if ((value != null))
					{
						value.tblDemogs.Add(this);
						this._HastaID = value.ID;
					}
					else
					{
						this._HastaID = default(Nullable<int>);
					}
					this.SendPropertyChanged("tblHasta");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tblDoktor")]
	public partial class tblDoktor : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _ID;
		
		private string _DAdi;
		
		private string _Dsoyadi;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIDChanging(int value);
    partial void OnIDChanged();
    partial void OnDAdiChanging(string value);
    partial void OnDAdiChanged();
    partial void OnDsoyadiChanging(string value);
    partial void OnDsoyadiChanged();
    #endregion
		
		public tblDoktor()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int ID
		{
			get
			{
				return this._ID;
			}
			set
			{
				if ((this._ID != value))
				{
					this.OnIDChanging(value);
					this.SendPropertyChanging();
					this._ID = value;
					this.SendPropertyChanged("ID");
					this.OnIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DAdi", DbType="NVarChar(50)")]
		public string DAdi
		{
			get
			{
				return this._DAdi;
			}
			set
			{
				if ((this._DAdi != value))
				{
					this.OnDAdiChanging(value);
					this.SendPropertyChanging();
					this._DAdi = value;
					this.SendPropertyChanged("DAdi");
					this.OnDAdiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Dsoyadi", DbType="NVarChar(50)")]
		public string Dsoyadi
		{
			get
			{
				return this._Dsoyadi;
			}
			set
			{
				if ((this._Dsoyadi != value))
				{
					this.OnDsoyadiChanging(value);
					this.SendPropertyChanging();
					this._Dsoyadi = value;
					this.SendPropertyChanged("Dsoyadi");
					this.OnDsoyadiChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tblHasta")]
	public partial class tblHasta : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _ID;
		
		private string _HAdi;
		
		private string _HSoyadi;
		
		private string _Protokol;
		
		private System.Nullable<System.DateTime> _OpTarihi;
		
		private string _OpTuru;
		
		private System.Nullable<int> _Takip;
		
		private System.Nullable<int> _Anah;
		
		private System.Nullable<int> _HastaNo;
		
		private EntitySet<tblDemog> _tblDemogs;
		
		private EntitySet<tblOperatif> _tblOperatifs;
		
		private EntitySet<tblPatoloji> _tblPatolojis;
		
		private EntitySet<tblTakipVerileri> _tblTakipVerileris;
		
		private EntitySet<tblPosOperatif> _tblPosOperatifs;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIDChanging(int value);
    partial void OnIDChanged();
    partial void OnHAdiChanging(string value);
    partial void OnHAdiChanged();
    partial void OnHSoyadiChanging(string value);
    partial void OnHSoyadiChanged();
    partial void OnProtokolChanging(string value);
    partial void OnProtokolChanged();
    partial void OnOpTarihiChanging(System.Nullable<System.DateTime> value);
    partial void OnOpTarihiChanged();
    partial void OnOpTuruChanging(string value);
    partial void OnOpTuruChanged();
    partial void OnTakipChanging(System.Nullable<int> value);
    partial void OnTakipChanged();
    partial void OnAnahChanging(System.Nullable<int> value);
    partial void OnAnahChanged();
    partial void OnHastaNoChanging(System.Nullable<int> value);
    partial void OnHastaNoChanged();
    #endregion
		
		public tblHasta()
		{
			this._tblDemogs = new EntitySet<tblDemog>(new Action<tblDemog>(this.attach_tblDemogs), new Action<tblDemog>(this.detach_tblDemogs));
			this._tblOperatifs = new EntitySet<tblOperatif>(new Action<tblOperatif>(this.attach_tblOperatifs), new Action<tblOperatif>(this.detach_tblOperatifs));
			this._tblPatolojis = new EntitySet<tblPatoloji>(new Action<tblPatoloji>(this.attach_tblPatolojis), new Action<tblPatoloji>(this.detach_tblPatolojis));
			this._tblTakipVerileris = new EntitySet<tblTakipVerileri>(new Action<tblTakipVerileri>(this.attach_tblTakipVerileris), new Action<tblTakipVerileri>(this.detach_tblTakipVerileris));
			this._tblPosOperatifs = new EntitySet<tblPosOperatif>(new Action<tblPosOperatif>(this.attach_tblPosOperatifs), new Action<tblPosOperatif>(this.detach_tblPosOperatifs));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int ID
		{
			get
			{
				return this._ID;
			}
			set
			{
				if ((this._ID != value))
				{
					this.OnIDChanging(value);
					this.SendPropertyChanging();
					this._ID = value;
					this.SendPropertyChanged("ID");
					this.OnIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_HAdi", DbType="NVarChar(50)")]
		public string HAdi
		{
			get
			{
				return this._HAdi;
			}
			set
			{
				if ((this._HAdi != value))
				{
					this.OnHAdiChanging(value);
					this.SendPropertyChanging();
					this._HAdi = value;
					this.SendPropertyChanged("HAdi");
					this.OnHAdiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_HSoyadi", DbType="NVarChar(50)")]
		public string HSoyadi
		{
			get
			{
				return this._HSoyadi;
			}
			set
			{
				if ((this._HSoyadi != value))
				{
					this.OnHSoyadiChanging(value);
					this.SendPropertyChanging();
					this._HSoyadi = value;
					this.SendPropertyChanged("HSoyadi");
					this.OnHSoyadiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Protokol", DbType="NVarChar(50)")]
		public string Protokol
		{
			get
			{
				return this._Protokol;
			}
			set
			{
				if ((this._Protokol != value))
				{
					this.OnProtokolChanging(value);
					this.SendPropertyChanging();
					this._Protokol = value;
					this.SendPropertyChanged("Protokol");
					this.OnProtokolChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_OpTarihi", DbType="Date")]
		public System.Nullable<System.DateTime> OpTarihi
		{
			get
			{
				return this._OpTarihi;
			}
			set
			{
				if ((this._OpTarihi != value))
				{
					this.OnOpTarihiChanging(value);
					this.SendPropertyChanging();
					this._OpTarihi = value;
					this.SendPropertyChanged("OpTarihi");
					this.OnOpTarihiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_OpTuru", DbType="NVarChar(50)")]
		public string OpTuru
		{
			get
			{
				return this._OpTuru;
			}
			set
			{
				if ((this._OpTuru != value))
				{
					this.OnOpTuruChanging(value);
					this.SendPropertyChanging();
					this._OpTuru = value;
					this.SendPropertyChanged("OpTuru");
					this.OnOpTuruChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Takip", DbType="Int")]
		public System.Nullable<int> Takip
		{
			get
			{
				return this._Takip;
			}
			set
			{
				if ((this._Takip != value))
				{
					this.OnTakipChanging(value);
					this.SendPropertyChanging();
					this._Takip = value;
					this.SendPropertyChanged("Takip");
					this.OnTakipChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Anah", DbType="Int")]
		public System.Nullable<int> Anah
		{
			get
			{
				return this._Anah;
			}
			set
			{
				if ((this._Anah != value))
				{
					this.OnAnahChanging(value);
					this.SendPropertyChanging();
					this._Anah = value;
					this.SendPropertyChanged("Anah");
					this.OnAnahChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_HastaNo", DbType="Int")]
		public System.Nullable<int> HastaNo
		{
			get
			{
				return this._HastaNo;
			}
			set
			{
				if ((this._HastaNo != value))
				{
					this.OnHastaNoChanging(value);
					this.SendPropertyChanging();
					this._HastaNo = value;
					this.SendPropertyChanged("HastaNo");
					this.OnHastaNoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tblHasta_tblDemog", Storage="_tblDemogs", ThisKey="ID", OtherKey="HastaID")]
		public EntitySet<tblDemog> tblDemogs
		{
			get
			{
				return this._tblDemogs;
			}
			set
			{
				this._tblDemogs.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tblHasta_tblOperatif", Storage="_tblOperatifs", ThisKey="ID", OtherKey="HastaID")]
		public EntitySet<tblOperatif> tblOperatifs
		{
			get
			{
				return this._tblOperatifs;
			}
			set
			{
				this._tblOperatifs.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tblHasta_tblPatoloji", Storage="_tblPatolojis", ThisKey="ID", OtherKey="HastaID")]
		public EntitySet<tblPatoloji> tblPatolojis
		{
			get
			{
				return this._tblPatolojis;
			}
			set
			{
				this._tblPatolojis.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tblHasta_tblTakipVerileri", Storage="_tblTakipVerileris", ThisKey="ID", OtherKey="HastaID")]
		public EntitySet<tblTakipVerileri> tblTakipVerileris
		{
			get
			{
				return this._tblTakipVerileris;
			}
			set
			{
				this._tblTakipVerileris.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tblHasta_tblPosOperatif", Storage="_tblPosOperatifs", ThisKey="ID", OtherKey="HastaID")]
		public EntitySet<tblPosOperatif> tblPosOperatifs
		{
			get
			{
				return this._tblPosOperatifs;
			}
			set
			{
				this._tblPosOperatifs.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_tblDemogs(tblDemog entity)
		{
			this.SendPropertyChanging();
			entity.tblHasta = this;
		}
		
		private void detach_tblDemogs(tblDemog entity)
		{
			this.SendPropertyChanging();
			entity.tblHasta = null;
		}
		
		private void attach_tblOperatifs(tblOperatif entity)
		{
			this.SendPropertyChanging();
			entity.tblHasta = this;
		}
		
		private void detach_tblOperatifs(tblOperatif entity)
		{
			this.SendPropertyChanging();
			entity.tblHasta = null;
		}
		
		private void attach_tblPatolojis(tblPatoloji entity)
		{
			this.SendPropertyChanging();
			entity.tblHasta = this;
		}
		
		private void detach_tblPatolojis(tblPatoloji entity)
		{
			this.SendPropertyChanging();
			entity.tblHasta = null;
		}
		
		private void attach_tblTakipVerileris(tblTakipVerileri entity)
		{
			this.SendPropertyChanging();
			entity.tblHasta = this;
		}
		
		private void detach_tblTakipVerileris(tblTakipVerileri entity)
		{
			this.SendPropertyChanging();
			entity.tblHasta = null;
		}
		
		private void attach_tblPosOperatifs(tblPosOperatif entity)
		{
			this.SendPropertyChanging();
			entity.tblHasta = this;
		}
		
		private void detach_tblPosOperatifs(tblPosOperatif entity)
		{
			this.SendPropertyChanging();
			entity.tblHasta = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tblKoMorbidite")]
	public partial class tblKoMorbidite : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _ID;
		
		private string _Komorbidite;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIDChanging(int value);
    partial void OnIDChanged();
    partial void OnKomorbiditeChanging(string value);
    partial void OnKomorbiditeChanged();
    #endregion
		
		public tblKoMorbidite()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int ID
		{
			get
			{
				return this._ID;
			}
			set
			{
				if ((this._ID != value))
				{
					this.OnIDChanging(value);
					this.SendPropertyChanging();
					this._ID = value;
					this.SendPropertyChanged("ID");
					this.OnIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Komorbidite", DbType="NVarChar(100)")]
		public string Komorbidite
		{
			get
			{
				return this._Komorbidite;
			}
			set
			{
				if ((this._Komorbidite != value))
				{
					this.OnKomorbiditeChanging(value);
					this.SendPropertyChanging();
					this._Komorbidite = value;
					this.SendPropertyChanged("Komorbidite");
					this.OnKomorbiditeChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tblOperatif")]
	public partial class tblOperatif : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _ID;
		
		private System.Nullable<int> _HastaID;
		
		private string _PksAciklama;
		
		private string _Sik;
		
		private string _CoOperasyon;
		
		private System.Nullable<int> _Iskemi;
		
		private System.Nullable<int> _PortSayisi;
		
		private string _YardimYnt;
		
		private System.Nullable<int> _Sure;
		
		private string _Dren;
		
		private System.Nullable<int> _Kanama;
		
		private string _Piyes;
		
		private EntityRef<tblHasta> _tblHasta;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIDChanging(int value);
    partial void OnIDChanged();
    partial void OnHastaIDChanging(System.Nullable<int> value);
    partial void OnHastaIDChanged();
    partial void OnPksAciklamaChanging(string value);
    partial void OnPksAciklamaChanged();
    partial void OnSikChanging(string value);
    partial void OnSikChanged();
    partial void OnCoOperasyonChanging(string value);
    partial void OnCoOperasyonChanged();
    partial void OnIskemiChanging(System.Nullable<int> value);
    partial void OnIskemiChanged();
    partial void OnPortSayisiChanging(System.Nullable<int> value);
    partial void OnPortSayisiChanged();
    partial void OnYardimYntChanging(string value);
    partial void OnYardimYntChanged();
    partial void OnSureChanging(System.Nullable<int> value);
    partial void OnSureChanged();
    partial void OnDrenChanging(string value);
    partial void OnDrenChanged();
    partial void OnKanamaChanging(System.Nullable<int> value);
    partial void OnKanamaChanged();
    partial void OnPiyesChanging(string value);
    partial void OnPiyesChanged();
    #endregion
		
		public tblOperatif()
		{
			this._tblHasta = default(EntityRef<tblHasta>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int ID
		{
			get
			{
				return this._ID;
			}
			set
			{
				if ((this._ID != value))
				{
					this.OnIDChanging(value);
					this.SendPropertyChanging();
					this._ID = value;
					this.SendPropertyChanged("ID");
					this.OnIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_HastaID", DbType="Int")]
		public System.Nullable<int> HastaID
		{
			get
			{
				return this._HastaID;
			}
			set
			{
				if ((this._HastaID != value))
				{
					if (this._tblHasta.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnHastaIDChanging(value);
					this.SendPropertyChanging();
					this._HastaID = value;
					this.SendPropertyChanged("HastaID");
					this.OnHastaIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PksAciklama", DbType="NVarChar(15)")]
		public string PksAciklama
		{
			get
			{
				return this._PksAciklama;
			}
			set
			{
				if ((this._PksAciklama != value))
				{
					this.OnPksAciklamaChanging(value);
					this.SendPropertyChanging();
					this._PksAciklama = value;
					this.SendPropertyChanged("PksAciklama");
					this.OnPksAciklamaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Sik", DbType="NVarChar(50)")]
		public string Sik
		{
			get
			{
				return this._Sik;
			}
			set
			{
				if ((this._Sik != value))
				{
					this.OnSikChanging(value);
					this.SendPropertyChanging();
					this._Sik = value;
					this.SendPropertyChanged("Sik");
					this.OnSikChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CoOperasyon", DbType="NVarChar(50)")]
		public string CoOperasyon
		{
			get
			{
				return this._CoOperasyon;
			}
			set
			{
				if ((this._CoOperasyon != value))
				{
					this.OnCoOperasyonChanging(value);
					this.SendPropertyChanging();
					this._CoOperasyon = value;
					this.SendPropertyChanged("CoOperasyon");
					this.OnCoOperasyonChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Iskemi", DbType="Int")]
		public System.Nullable<int> Iskemi
		{
			get
			{
				return this._Iskemi;
			}
			set
			{
				if ((this._Iskemi != value))
				{
					this.OnIskemiChanging(value);
					this.SendPropertyChanging();
					this._Iskemi = value;
					this.SendPropertyChanged("Iskemi");
					this.OnIskemiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PortSayisi", DbType="Int")]
		public System.Nullable<int> PortSayisi
		{
			get
			{
				return this._PortSayisi;
			}
			set
			{
				if ((this._PortSayisi != value))
				{
					this.OnPortSayisiChanging(value);
					this.SendPropertyChanging();
					this._PortSayisi = value;
					this.SendPropertyChanged("PortSayisi");
					this.OnPortSayisiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_YardimYnt", DbType="NVarChar(50)")]
		public string YardimYnt
		{
			get
			{
				return this._YardimYnt;
			}
			set
			{
				if ((this._YardimYnt != value))
				{
					this.OnYardimYntChanging(value);
					this.SendPropertyChanging();
					this._YardimYnt = value;
					this.SendPropertyChanged("YardimYnt");
					this.OnYardimYntChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Sure", DbType="Int")]
		public System.Nullable<int> Sure
		{
			get
			{
				return this._Sure;
			}
			set
			{
				if ((this._Sure != value))
				{
					this.OnSureChanging(value);
					this.SendPropertyChanging();
					this._Sure = value;
					this.SendPropertyChanged("Sure");
					this.OnSureChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Dren", DbType="NVarChar(50)")]
		public string Dren
		{
			get
			{
				return this._Dren;
			}
			set
			{
				if ((this._Dren != value))
				{
					this.OnDrenChanging(value);
					this.SendPropertyChanging();
					this._Dren = value;
					this.SendPropertyChanged("Dren");
					this.OnDrenChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Kanama", DbType="Int")]
		public System.Nullable<int> Kanama
		{
			get
			{
				return this._Kanama;
			}
			set
			{
				if ((this._Kanama != value))
				{
					this.OnKanamaChanging(value);
					this.SendPropertyChanging();
					this._Kanama = value;
					this.SendPropertyChanged("Kanama");
					this.OnKanamaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Piyes", DbType="NVarChar(50)")]
		public string Piyes
		{
			get
			{
				return this._Piyes;
			}
			set
			{
				if ((this._Piyes != value))
				{
					this.OnPiyesChanging(value);
					this.SendPropertyChanging();
					this._Piyes = value;
					this.SendPropertyChanged("Piyes");
					this.OnPiyesChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tblHasta_tblOperatif", Storage="_tblHasta", ThisKey="HastaID", OtherKey="ID", IsForeignKey=true)]
		public tblHasta tblHasta
		{
			get
			{
				return this._tblHasta.Entity;
			}
			set
			{
				tblHasta previousValue = this._tblHasta.Entity;
				if (((previousValue != value) 
							|| (this._tblHasta.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._tblHasta.Entity = null;
						previousValue.tblOperatifs.Remove(this);
					}
					this._tblHasta.Entity = value;
					if ((value != null))
					{
						value.tblOperatifs.Add(this);
						this._HastaID = value.ID;
					}
					else
					{
						this._HastaID = default(Nullable<int>);
					}
					this.SendPropertyChanged("tblHasta");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tblOpTuru")]
	public partial class tblOpTuru : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _ID;
		
		private string _OpTuru;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIDChanging(int value);
    partial void OnIDChanged();
    partial void OnOpTuruChanging(string value);
    partial void OnOpTuruChanged();
    #endregion
		
		public tblOpTuru()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int ID
		{
			get
			{
				return this._ID;
			}
			set
			{
				if ((this._ID != value))
				{
					this.OnIDChanging(value);
					this.SendPropertyChanging();
					this._ID = value;
					this.SendPropertyChanged("ID");
					this.OnIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_OpTuru", DbType="NVarChar(100)")]
		public string OpTuru
		{
			get
			{
				return this._OpTuru;
			}
			set
			{
				if ((this._OpTuru != value))
				{
					this.OnOpTuruChanging(value);
					this.SendPropertyChanging();
					this._OpTuru = value;
					this.SendPropertyChanged("OpTuru");
					this.OnOpTuruChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tblPatoloji")]
	public partial class tblPatoloji : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _ID;
		
		private System.Nullable<int> _HastaID;
		
		private string _Patoloji;
		
		private string _AltGrup;
		
		private string _FurhmanGrade;
		
		private string _PatoEvre;
		
		private string _CerrahiSinir;
		
		private EntityRef<tblHasta> _tblHasta;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIDChanging(int value);
    partial void OnIDChanged();
    partial void OnHastaIDChanging(System.Nullable<int> value);
    partial void OnHastaIDChanged();
    partial void OnPatolojiChanging(string value);
    partial void OnPatolojiChanged();
    partial void OnAltGrupChanging(string value);
    partial void OnAltGrupChanged();
    partial void OnFurhmanGradeChanging(string value);
    partial void OnFurhmanGradeChanged();
    partial void OnPatoEvreChanging(string value);
    partial void OnPatoEvreChanged();
    partial void OnCerrahiSinirChanging(string value);
    partial void OnCerrahiSinirChanged();
    #endregion
		
		public tblPatoloji()
		{
			this._tblHasta = default(EntityRef<tblHasta>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int ID
		{
			get
			{
				return this._ID;
			}
			set
			{
				if ((this._ID != value))
				{
					this.OnIDChanging(value);
					this.SendPropertyChanging();
					this._ID = value;
					this.SendPropertyChanged("ID");
					this.OnIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_HastaID", DbType="Int")]
		public System.Nullable<int> HastaID
		{
			get
			{
				return this._HastaID;
			}
			set
			{
				if ((this._HastaID != value))
				{
					if (this._tblHasta.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnHastaIDChanging(value);
					this.SendPropertyChanging();
					this._HastaID = value;
					this.SendPropertyChanged("HastaID");
					this.OnHastaIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Patoloji", DbType="NVarChar(50)")]
		public string Patoloji
		{
			get
			{
				return this._Patoloji;
			}
			set
			{
				if ((this._Patoloji != value))
				{
					this.OnPatolojiChanging(value);
					this.SendPropertyChanging();
					this._Patoloji = value;
					this.SendPropertyChanged("Patoloji");
					this.OnPatolojiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AltGrup", DbType="NVarChar(50)")]
		public string AltGrup
		{
			get
			{
				return this._AltGrup;
			}
			set
			{
				if ((this._AltGrup != value))
				{
					this.OnAltGrupChanging(value);
					this.SendPropertyChanging();
					this._AltGrup = value;
					this.SendPropertyChanged("AltGrup");
					this.OnAltGrupChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FurhmanGrade", DbType="NVarChar(50)")]
		public string FurhmanGrade
		{
			get
			{
				return this._FurhmanGrade;
			}
			set
			{
				if ((this._FurhmanGrade != value))
				{
					this.OnFurhmanGradeChanging(value);
					this.SendPropertyChanging();
					this._FurhmanGrade = value;
					this.SendPropertyChanged("FurhmanGrade");
					this.OnFurhmanGradeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PatoEvre", DbType="NVarChar(15)")]
		public string PatoEvre
		{
			get
			{
				return this._PatoEvre;
			}
			set
			{
				if ((this._PatoEvre != value))
				{
					this.OnPatoEvreChanging(value);
					this.SendPropertyChanging();
					this._PatoEvre = value;
					this.SendPropertyChanged("PatoEvre");
					this.OnPatoEvreChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CerrahiSinir", DbType="NVarChar(50)")]
		public string CerrahiSinir
		{
			get
			{
				return this._CerrahiSinir;
			}
			set
			{
				if ((this._CerrahiSinir != value))
				{
					this.OnCerrahiSinirChanging(value);
					this.SendPropertyChanging();
					this._CerrahiSinir = value;
					this.SendPropertyChanged("CerrahiSinir");
					this.OnCerrahiSinirChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tblHasta_tblPatoloji", Storage="_tblHasta", ThisKey="HastaID", OtherKey="ID", IsForeignKey=true)]
		public tblHasta tblHasta
		{
			get
			{
				return this._tblHasta.Entity;
			}
			set
			{
				tblHasta previousValue = this._tblHasta.Entity;
				if (((previousValue != value) 
							|| (this._tblHasta.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._tblHasta.Entity = null;
						previousValue.tblPatolojis.Remove(this);
					}
					this._tblHasta.Entity = value;
					if ((value != null))
					{
						value.tblPatolojis.Add(this);
						this._HastaID = value.ID;
					}
					else
					{
						this._HastaID = default(Nullable<int>);
					}
					this.SendPropertyChanged("tblHasta");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tblTakipVerileri")]
	public partial class tblTakipVerileri : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _ID;
		
		private System.Nullable<int> _HastaID;
		
		private string _PUcLokal;
		
		private System.Nullable<decimal> _PUcKreatin;
		
		private string _PAltiLokal;
		
		private System.Nullable<decimal> _PAltiKreatin;
		
		private string _POnikiLokal;
		
		private System.Nullable<decimal> _POnikiKreatin;
		
		private EntityRef<tblHasta> _tblHasta;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIDChanging(int value);
    partial void OnIDChanged();
    partial void OnHastaIDChanging(System.Nullable<int> value);
    partial void OnHastaIDChanged();
    partial void OnPUcLokalChanging(string value);
    partial void OnPUcLokalChanged();
    partial void OnPUcKreatinChanging(System.Nullable<decimal> value);
    partial void OnPUcKreatinChanged();
    partial void OnPAltiLokalChanging(string value);
    partial void OnPAltiLokalChanged();
    partial void OnPAltiKreatinChanging(System.Nullable<decimal> value);
    partial void OnPAltiKreatinChanged();
    partial void OnPOnikiLokalChanging(string value);
    partial void OnPOnikiLokalChanged();
    partial void OnPOnikiKreatinChanging(System.Nullable<decimal> value);
    partial void OnPOnikiKreatinChanged();
    #endregion
		
		public tblTakipVerileri()
		{
			this._tblHasta = default(EntityRef<tblHasta>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int ID
		{
			get
			{
				return this._ID;
			}
			set
			{
				if ((this._ID != value))
				{
					this.OnIDChanging(value);
					this.SendPropertyChanging();
					this._ID = value;
					this.SendPropertyChanged("ID");
					this.OnIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_HastaID", DbType="Int")]
		public System.Nullable<int> HastaID
		{
			get
			{
				return this._HastaID;
			}
			set
			{
				if ((this._HastaID != value))
				{
					if (this._tblHasta.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnHastaIDChanging(value);
					this.SendPropertyChanging();
					this._HastaID = value;
					this.SendPropertyChanged("HastaID");
					this.OnHastaIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PUcLokal", DbType="NVarChar(50)")]
		public string PUcLokal
		{
			get
			{
				return this._PUcLokal;
			}
			set
			{
				if ((this._PUcLokal != value))
				{
					this.OnPUcLokalChanging(value);
					this.SendPropertyChanging();
					this._PUcLokal = value;
					this.SendPropertyChanged("PUcLokal");
					this.OnPUcLokalChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PUcKreatin", DbType="Decimal(5,2)")]
		public System.Nullable<decimal> PUcKreatin
		{
			get
			{
				return this._PUcKreatin;
			}
			set
			{
				if ((this._PUcKreatin != value))
				{
					this.OnPUcKreatinChanging(value);
					this.SendPropertyChanging();
					this._PUcKreatin = value;
					this.SendPropertyChanged("PUcKreatin");
					this.OnPUcKreatinChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PAltiLokal", DbType="NVarChar(50)")]
		public string PAltiLokal
		{
			get
			{
				return this._PAltiLokal;
			}
			set
			{
				if ((this._PAltiLokal != value))
				{
					this.OnPAltiLokalChanging(value);
					this.SendPropertyChanging();
					this._PAltiLokal = value;
					this.SendPropertyChanged("PAltiLokal");
					this.OnPAltiLokalChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PAltiKreatin", DbType="Decimal(5,2)")]
		public System.Nullable<decimal> PAltiKreatin
		{
			get
			{
				return this._PAltiKreatin;
			}
			set
			{
				if ((this._PAltiKreatin != value))
				{
					this.OnPAltiKreatinChanging(value);
					this.SendPropertyChanging();
					this._PAltiKreatin = value;
					this.SendPropertyChanged("PAltiKreatin");
					this.OnPAltiKreatinChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_POnikiLokal", DbType="NVarChar(50)")]
		public string POnikiLokal
		{
			get
			{
				return this._POnikiLokal;
			}
			set
			{
				if ((this._POnikiLokal != value))
				{
					this.OnPOnikiLokalChanging(value);
					this.SendPropertyChanging();
					this._POnikiLokal = value;
					this.SendPropertyChanged("POnikiLokal");
					this.OnPOnikiLokalChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_POnikiKreatin", DbType="Decimal(5,2)")]
		public System.Nullable<decimal> POnikiKreatin
		{
			get
			{
				return this._POnikiKreatin;
			}
			set
			{
				if ((this._POnikiKreatin != value))
				{
					this.OnPOnikiKreatinChanging(value);
					this.SendPropertyChanging();
					this._POnikiKreatin = value;
					this.SendPropertyChanged("POnikiKreatin");
					this.OnPOnikiKreatinChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tblHasta_tblTakipVerileri", Storage="_tblHasta", ThisKey="HastaID", OtherKey="ID", IsForeignKey=true)]
		public tblHasta tblHasta
		{
			get
			{
				return this._tblHasta.Entity;
			}
			set
			{
				tblHasta previousValue = this._tblHasta.Entity;
				if (((previousValue != value) 
							|| (this._tblHasta.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._tblHasta.Entity = null;
						previousValue.tblTakipVerileris.Remove(this);
					}
					this._tblHasta.Entity = value;
					if ((value != null))
					{
						value.tblTakipVerileris.Add(this);
						this._HastaID = value.ID;
					}
					else
					{
						this._HastaID = default(Nullable<int>);
					}
					this.SendPropertyChanged("tblHasta");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tblPosOperatif")]
	public partial class tblPosOperatif : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _ID;
		
		private System.Nullable<int> _HastaID;
		
		private string _PerErKomp;
		
		private string _Dren;
		
		private string _PostAnaliz;
		
		private string _Sonda;
		
		private System.Nullable<int> _HospSuresi;
		
		private System.Nullable<decimal> _PreopKreatin;
		
		private System.Nullable<decimal> _PostopKreatin;
		
		private System.Nullable<decimal> _PreopHtc;
		
		private System.Nullable<decimal> _PostopHtc;
		
		private System.Nullable<decimal> _PreopHb;
		
		private System.Nullable<decimal> _PostopHb;
		
		private string _Takip;
		
		private string _Tel;
		
		private string _PostopGec;
		
		private string _KompClavien;
		
		private EntityRef<tblHasta> _tblHasta;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIDChanging(int value);
    partial void OnIDChanged();
    partial void OnHastaIDChanging(System.Nullable<int> value);
    partial void OnHastaIDChanged();
    partial void OnPerErKompChanging(string value);
    partial void OnPerErKompChanged();
    partial void OnDrenChanging(string value);
    partial void OnDrenChanged();
    partial void OnPostAnalizChanging(string value);
    partial void OnPostAnalizChanged();
    partial void OnSondaChanging(string value);
    partial void OnSondaChanged();
    partial void OnHospSuresiChanging(System.Nullable<int> value);
    partial void OnHospSuresiChanged();
    partial void OnPreopKreatinChanging(System.Nullable<decimal> value);
    partial void OnPreopKreatinChanged();
    partial void OnPostopKreatinChanging(System.Nullable<decimal> value);
    partial void OnPostopKreatinChanged();
    partial void OnPreopHtcChanging(System.Nullable<decimal> value);
    partial void OnPreopHtcChanged();
    partial void OnPostopHtcChanging(System.Nullable<decimal> value);
    partial void OnPostopHtcChanged();
    partial void OnPreopHbChanging(System.Nullable<decimal> value);
    partial void OnPreopHbChanged();
    partial void OnPostopHbChanging(System.Nullable<decimal> value);
    partial void OnPostopHbChanged();
    partial void OnTakipChanging(string value);
    partial void OnTakipChanged();
    partial void OnTelChanging(string value);
    partial void OnTelChanged();
    partial void OnPostopGecChanging(string value);
    partial void OnPostopGecChanged();
    partial void OnKompClavienChanging(string value);
    partial void OnKompClavienChanged();
    #endregion
		
		public tblPosOperatif()
		{
			this._tblHasta = default(EntityRef<tblHasta>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int ID
		{
			get
			{
				return this._ID;
			}
			set
			{
				if ((this._ID != value))
				{
					this.OnIDChanging(value);
					this.SendPropertyChanging();
					this._ID = value;
					this.SendPropertyChanged("ID");
					this.OnIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_HastaID", DbType="Int")]
		public System.Nullable<int> HastaID
		{
			get
			{
				return this._HastaID;
			}
			set
			{
				if ((this._HastaID != value))
				{
					if (this._tblHasta.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnHastaIDChanging(value);
					this.SendPropertyChanging();
					this._HastaID = value;
					this.SendPropertyChanged("HastaID");
					this.OnHastaIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PerErKomp", DbType="NVarChar(50)")]
		public string PerErKomp
		{
			get
			{
				return this._PerErKomp;
			}
			set
			{
				if ((this._PerErKomp != value))
				{
					this.OnPerErKompChanging(value);
					this.SendPropertyChanging();
					this._PerErKomp = value;
					this.SendPropertyChanged("PerErKomp");
					this.OnPerErKompChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Dren", DbType="NVarChar(50)")]
		public string Dren
		{
			get
			{
				return this._Dren;
			}
			set
			{
				if ((this._Dren != value))
				{
					this.OnDrenChanging(value);
					this.SendPropertyChanging();
					this._Dren = value;
					this.SendPropertyChanged("Dren");
					this.OnDrenChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PostAnaliz", DbType="NVarChar(50)")]
		public string PostAnaliz
		{
			get
			{
				return this._PostAnaliz;
			}
			set
			{
				if ((this._PostAnaliz != value))
				{
					this.OnPostAnalizChanging(value);
					this.SendPropertyChanging();
					this._PostAnaliz = value;
					this.SendPropertyChanged("PostAnaliz");
					this.OnPostAnalizChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Sonda", DbType="NVarChar(50)")]
		public string Sonda
		{
			get
			{
				return this._Sonda;
			}
			set
			{
				if ((this._Sonda != value))
				{
					this.OnSondaChanging(value);
					this.SendPropertyChanging();
					this._Sonda = value;
					this.SendPropertyChanged("Sonda");
					this.OnSondaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_HospSuresi", DbType="Int")]
		public System.Nullable<int> HospSuresi
		{
			get
			{
				return this._HospSuresi;
			}
			set
			{
				if ((this._HospSuresi != value))
				{
					this.OnHospSuresiChanging(value);
					this.SendPropertyChanging();
					this._HospSuresi = value;
					this.SendPropertyChanged("HospSuresi");
					this.OnHospSuresiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PreopKreatin", DbType="Decimal(5,2)")]
		public System.Nullable<decimal> PreopKreatin
		{
			get
			{
				return this._PreopKreatin;
			}
			set
			{
				if ((this._PreopKreatin != value))
				{
					this.OnPreopKreatinChanging(value);
					this.SendPropertyChanging();
					this._PreopKreatin = value;
					this.SendPropertyChanged("PreopKreatin");
					this.OnPreopKreatinChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PostopKreatin", DbType="Decimal(5,2)")]
		public System.Nullable<decimal> PostopKreatin
		{
			get
			{
				return this._PostopKreatin;
			}
			set
			{
				if ((this._PostopKreatin != value))
				{
					this.OnPostopKreatinChanging(value);
					this.SendPropertyChanging();
					this._PostopKreatin = value;
					this.SendPropertyChanged("PostopKreatin");
					this.OnPostopKreatinChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PreopHtc", DbType="Decimal(5,2)")]
		public System.Nullable<decimal> PreopHtc
		{
			get
			{
				return this._PreopHtc;
			}
			set
			{
				if ((this._PreopHtc != value))
				{
					this.OnPreopHtcChanging(value);
					this.SendPropertyChanging();
					this._PreopHtc = value;
					this.SendPropertyChanged("PreopHtc");
					this.OnPreopHtcChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PostopHtc", DbType="Decimal(5,2)")]
		public System.Nullable<decimal> PostopHtc
		{
			get
			{
				return this._PostopHtc;
			}
			set
			{
				if ((this._PostopHtc != value))
				{
					this.OnPostopHtcChanging(value);
					this.SendPropertyChanging();
					this._PostopHtc = value;
					this.SendPropertyChanged("PostopHtc");
					this.OnPostopHtcChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PreopHb", DbType="Decimal(5,2)")]
		public System.Nullable<decimal> PreopHb
		{
			get
			{
				return this._PreopHb;
			}
			set
			{
				if ((this._PreopHb != value))
				{
					this.OnPreopHbChanging(value);
					this.SendPropertyChanging();
					this._PreopHb = value;
					this.SendPropertyChanged("PreopHb");
					this.OnPreopHbChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PostopHb", DbType="Decimal(5,2)")]
		public System.Nullable<decimal> PostopHb
		{
			get
			{
				return this._PostopHb;
			}
			set
			{
				if ((this._PostopHb != value))
				{
					this.OnPostopHbChanging(value);
					this.SendPropertyChanging();
					this._PostopHb = value;
					this.SendPropertyChanged("PostopHb");
					this.OnPostopHbChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Takip", DbType="NVarChar(100)")]
		public string Takip
		{
			get
			{
				return this._Takip;
			}
			set
			{
				if ((this._Takip != value))
				{
					this.OnTakipChanging(value);
					this.SendPropertyChanging();
					this._Takip = value;
					this.SendPropertyChanged("Takip");
					this.OnTakipChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Tel", DbType="NVarChar(100)")]
		public string Tel
		{
			get
			{
				return this._Tel;
			}
			set
			{
				if ((this._Tel != value))
				{
					this.OnTelChanging(value);
					this.SendPropertyChanging();
					this._Tel = value;
					this.SendPropertyChanged("Tel");
					this.OnTelChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PostopGec", DbType="NVarChar(50)")]
		public string PostopGec
		{
			get
			{
				return this._PostopGec;
			}
			set
			{
				if ((this._PostopGec != value))
				{
					this.OnPostopGecChanging(value);
					this.SendPropertyChanging();
					this._PostopGec = value;
					this.SendPropertyChanged("PostopGec");
					this.OnPostopGecChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_KompClavien", DbType="NVarChar(50)")]
		public string KompClavien
		{
			get
			{
				return this._KompClavien;
			}
			set
			{
				if ((this._KompClavien != value))
				{
					this.OnKompClavienChanging(value);
					this.SendPropertyChanging();
					this._KompClavien = value;
					this.SendPropertyChanged("KompClavien");
					this.OnKompClavienChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tblHasta_tblPosOperatif", Storage="_tblHasta", ThisKey="HastaID", OtherKey="ID", IsForeignKey=true)]
		public tblHasta tblHasta
		{
			get
			{
				return this._tblHasta.Entity;
			}
			set
			{
				tblHasta previousValue = this._tblHasta.Entity;
				if (((previousValue != value) 
							|| (this._tblHasta.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._tblHasta.Entity = null;
						previousValue.tblPosOperatifs.Remove(this);
					}
					this._tblHasta.Entity = value;
					if ((value != null))
					{
						value.tblPosOperatifs.Add(this);
						this._HastaID = value.ID;
					}
					else
					{
						this._HastaID = default(Nullable<int>);
					}
					this.SendPropertyChanged("tblHasta");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
}
#pragma warning restore 1591
